export const BADGE_DEFS = {
  chiacchierone: { emoji: '🎤', label: 'Il Chiacchierone', description: 'Più messaggi mandati nel gruppo, ultimi 7 giorni.' },
  banchiere: { emoji: '💰', label: 'Il Banchiere', description: 'Più spese pagate nel gruppo, ultimi 7 giorni.' },
  organizzatore: { emoji: '📅', label: "L'Organizzatore", description: 'Più eventi creati nel gruppo, ultimi 7 giorni.' },
  favorito: { emoji: '⭐', label: 'Il Favorito', description: 'Pagella media più alta nel gruppo (min. 3 voti), ultimi 7 giorni.' },
  caos: { emoji: '🌪️', label: 'Il Caos', description: 'Punteggio più alto in Caos nel gruppo, ultimi 7 giorni.' },
  roccia: { emoji: '🎯', label: 'La Roccia', description: 'Punteggio più alto in Affidabilità nel gruppo, ultimi 7 giorni.' },
  nottambulo: { emoji: '🌙', label: 'Il Nottambulo', description: 'Più messaggi tra mezzanotte e le 5 nel gruppo, ultimi 7 giorni.' },
  paparazzo: { emoji: '📸', label: 'Il Paparazzo', description: 'Più foto/video caricati nel gruppo, ultimi 7 giorni.' },
  presente: { emoji: '🥇', label: 'Il Presente', description: 'Ha votato la pagella per più eventi del gruppo, ultimi 7 giorni.' },
  politico: { emoji: '🗳️', label: 'Il Politico', description: 'Più proposte e sondaggi creati nel gruppo, ultimi 7 giorni.' },
  popolare: { emoji: '🔥', label: 'Il Popolare', description: 'I suoi messaggi ricevono più reazioni nel gruppo, ultimi 7 giorni.' },
  vocale: { emoji: '🎙️', label: 'Il Vocale-dipendente', description: 'Più messaggi vocali mandati nel gruppo, ultimi 7 giorni.' },
  spiantato: { emoji: '🪙', label: 'Lo Spiantato', description: 'Più quote di spesa ancora da pagare nel gruppo, in questo momento.' },
  soprannominato: { emoji: '🏷️', label: 'Il Soprannominato', description: 'Ha ricevuto più nickname dagli amici, ultimi 7 giorni.' },
}
